# Generated by Django 5.1.1 on 2024-10-04 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название компании')),
                ('company_history', models.TextField(blank=True, verbose_name='История компании')),
                ('description', models.TextField(blank=True, verbose_name='Описание компании')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='Дата основания')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Основной Email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Телефон')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город главного офиса')),
                ('address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('employees_count', models.IntegerField(default=0, verbose_name='Количество сотрудников')),
                ('legal_form', models.CharField(choices=[('OOO', 'ООО'), ('ZAO', 'ЗАО'), ('PAO', 'ПАО'), ('IP', 'ИП')], default='OOO', max_length=100, verbose_name='Юридическая форма')),
                ('inn', models.CharField(blank=True, max_length=10, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=13, unique=True, verbose_name='ОГРН')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название отдела')),
                ('description', models.TextField(blank=True, verbose_name='Описание отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='GeneralModelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('skills', models.TextField(blank=True, verbose_name='Навыки')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('date_of_employment', models.DateField(verbose_name='Дата трудоустройства')),
                ('date_of_dismissal', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Компания')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='accounts.department', verbose_name='Отдел')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='accounts.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to='accounts.generalmodelprofile', verbose_name='Руководитель'),
        ),
    ]
