# Generated by Django 5.1.1 on 2024-10-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_company_position_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ManyToManyField(to='accounts.department', verbose_name='Отдел'),
        ),
    ]
