# Generated by Django 5.1.1 on 2024-10-04 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_position_department_position_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmodelprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Компания'),
        ),
    ]
