# Generated by Django 5.1.1 on 2024-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_generalmodelprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='moderator',
            field=models.BooleanField(blank=True, null=True, verbose_name='Модератор'),
        ),
    ]
