# Generated by Django 5.1.1 on 2024-10-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_generalmodelprofile_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmodelprofile',
            name='fired',
            field=models.BooleanField(null=True, verbose_name='Уволен'),
        ),
    ]
