# Generated by Django 5.1.2 on 2024-10-09 19:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_generalmodelprofile_fired'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralModelProfile',
            new_name='Profile',
        ),
    ]
