# Generated by Django 5.1.2 on 2024-10-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_position_department_position_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='moderator',
        ),
        migrations.AddField(
            model_name='profile',
            name='moderator',
            field=models.BooleanField(blank=True, null=True, verbose_name='Модератор'),
        ),
    ]
